version: '3'
services:
  web:
    build: .
    command: gunicorn --reload --bind=0.0.0.0:8000 eahub.config.wsgi
    depends_on:
      - db
      - objstore
      - cache
      - mail
      - webdriver
      - chrome
      - firefox
    ports:
      - 8000:8000
    volumes:
      - .:/code
    env_file:
      - .env
  db:
    image: postgres:10.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: development_db_password
  objstore:
    image: arafato/azurite:2.6.5
    command: node bin/blob --location=/opt/azurite/folder/ --blobPort=8002
    ports:
      - 8002:8002
  cache:
    image: redis:3.2.7
    ports:
      - 6379:6379
  mail:
    image: dockage/mailcatcher:0.6.5
    ports:
      - 8001:1080
  webdriver:
    image: selenium/hub:3.141.59-iron
  chrome:
    image: selenium/node-chrome:3.141.59-iron
    depends_on:
      - webdriver
    environment:
      HUB_HOST: webdriver
  firefox:
    image: selenium/node-firefox:3.141.59-iron
    depends_on:
      - webdriver
    environment:
      HUB_HOST: webdriver
