version: '3'

services:
  web:
    build: .
    command: sh -c "django-admin migrate && gunicorn --reload --bind=0.0.0.0:8000 eahub.config.wsgi"
    depends_on:
      - db
      - objstore
      - cache
      - mail
      - webdriver
      - chrome
      - firefox
    ports:
      - 8000:8000
    volumes:
      - .:/code
    environment:
      APPLICATION_INSIGHTS_INSTRUMENTATION_KEY:
      LEGACY_DATABASE_URL:
      LOCAL_GROUPS_AIRTABLE_API_KEY:
      LOCAL_GROUPS_AIRTABLE_BASE_KEY:
      RECAPTCHA_V3_SECRET_KEY:
      RECAPTCHA_V3_SITE_KEY:
      ADMINS: Local Admin=admin@example.com
      AZURE_CONNECTION_STRING: UseDevelopmentStorage=true;BlobEndpoint=objstore:8002
      AZURE_CONTAINER: media
      BROWSERS: chrome,firefox
      CACHE_URL: redis://cache:6379/0
      DATABASE_URL: postgresql://postgres:development_db_password@db:5432/postgres
      DEBUG: 'True'
      DJANGO_LIVE_TEST_SERVER_ADDRESS: 'web'
      EMAIL_URL: smtp://mail:1025
      HOSTS: web,localhost
      HTTPS: 'False'
      LEAN_MANAGERS: Local Manager=leanmanager@example.com
      PYTEST_ADDOPTS: --driver=Remote
      PYTHONDONTWRITEBYTECODE: 'True'
      SECRET_KEY: development_secret_key
      SELENIUM_HOST: webdriver
  db:
    image: postgres:10.5
    environment:
      POSTGRES_PASSWORD: development_db_password
  objstore:
    image: arafato/azurite:2.6.5
    command: node bin/blob --location=/opt/azurite/folder/ --blobPort=8002
    ports:
      - 8002:8002
  cache:
    image: redis:3.2.7
  mail:
    image: dockage/mailcatcher:0.6.5
    ports:
      - 8001:1080
  webdriver:
    image: selenium/hub:3.141.59-iron
  chrome:
    image: selenium/node-chrome:3.141.59-iron
    depends_on:
      - webdriver
    environment:
      HUB_HOST: webdriver
  firefox:
    image: selenium/node-firefox:3.141.59-iron
    depends_on:
      - webdriver
    environment:
      HUB_HOST: webdriver
